import Head from "next/head";
import Image from "next/image";
// import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Banner from "@/components/home/Banner";
import Footer from "@/components/footer/Footer";
import Header from "@/components/header/Header";
import Categories from "@/components/explore-category/Categories";
import Faq from "@/components/faq/Faq";
import PropertyBox from "@/components/property-box/PropertyBox";
import InboxDetails from "@/components/inbox-details/InboxDetails";
import InboxContact from "@/components/inbox-contact/InboxContact";
import Testimonial from "@/components/testimonial/Testimonial";
import RentalForm from "@/components/rentalform/RentalForm";


// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Ayodhya Hotel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
       
      </Head>
      <Header />
       <Banner />
       {/* <RentalForm /> */}
       <PropertyBox />
       <Categories />
       <InboxDetails />
       <Testimonial />
        <InboxContact />
      <Faq />
      <Footer />
      
    </>
  );
}
